'use strict';
const $=id=>document.getElementById(id);

let frame=0,example=0,position=0,playing=false,inspected=null,selectedCell=null,modelSerial=0;
const maps=[];let currentTraceKey='',currentTrace;
const labels={tokenEmbedding:['Token embedding','文字の埋め込み。語彙の各文字に、学習可能な特徴ベクトルを割り当てます。'],positionEmbedding:['Position embedding','位置の埋め込み。同じ文字でも、位置によって異なる表現になります。このパラメータも学習します。'],embedding:['Embedding + position','文字と位置の埋め込みを成分ごとに足した、最初のブロックへの入力です。'],normAttention:['LayerNorm 1','各行を独立に正規化。平均0・分散約1の入力からQ/K/Vを計算します。'],q:['Q · Query','情報を探すためのベクトル。LayerNormされた入力と学習可能なWqの積です。'],k:['K · Key','参照先を照合するベクトル。QとKの内積が、注意を向ける強さのもとになります。'],v:['V · Value','注意の割合に応じて集められる情報。Attentionの重みでVを加重平均します。'],attention:['Causal attention','行＝情報を集める位置、列＝参照先。各行の合計は約1。未来の列は因果マスクによって0です。'],attentionOutput:['Attention projection','Attentionで集めたVを、学習可能なWoで元の次元の出力に変換した値です。'],attentionResidual:['Residual 1','Attentionへの入力に、Attention projectionを加えた値です。'],normFF:['LayerNorm 2','MLPへ渡す前に、各行を独立に正規化した値です。'],hidden:['MLP hidden · tanh','次元数を2倍に広げる線形変換後、tanhを適用。−1〜1の非線形な表現になります。'],ffOutput:['MLP projection','隠れ層を、入力次元に戻す線形変換の出力です。'],output:['Residual 2 · block output','Residual 1にMLP projectionを加えたブロック全体の出力です。次のブロックまたは最終LayerNormへ渡されます。'],finalNorm:['Final LayerNorm','最後のブロック出力を正規化し、語彙ごとのスコアに変換する準備をします。'],logits:['Output logits','特徴ベクトルから全語彙へ線形変換した、確率になる前のスコアです。'],probs:['Softmax probabilities','LogitsをSoftmaxで確率に変換。各行の合計が約1となり、次の1文字の分布を表します。']};
function current(){const key=modelSerial+':'+data.snapshots[frame].step+':'+example;if(key!==currentTraceKey){currentTrace=decoderTrace(data.snapshots[frame].weights,data.tokens[example].map(t=>data.vocab.indexOf(t)));currentTraceKey=key}return currentTrace}
function matrix(map){return map.block===undefined?current()[map.key]:current().blocks[map.block][map.key]}
function addMap(container,key,name,desc,block,wide=false,residual=false){const id='map-'+maps.length;const map={id,key,block,name,desc};maps.push(map);$(container).insertAdjacentHTML('beforeend',`<div class="tile ${wide?'wide':''} ${residual?'residual':''}"><div class="tile-head"><span class="tile-name">${name}</span><span class="tile-shape" id="${id}-shape"></span></div><canvas id="${id}" tabindex="0" role="img" aria-label="${block===undefined?'':`ブロック${block+1} `}${labels[key][0]}の全位置の値"></canvas></div>`);const c=$(id);c.addEventListener('pointermove',e=>inspectPointer(e,map,false));c.addEventListener('click',e=>inspectPointer(e,map,true));c.addEventListener('focus',()=>{inspected={map,row:position,col:0};showInspection()});c.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter'].includes(e.key))return;e.preventDefault();let v=matrix(map);if(!inspected||inspected.map!==map)inspected={map,row:position,col:0};if(e.key==='ArrowLeft')inspected.col=Math.max(0,inspected.col-1);if(e.key==='ArrowRight')inspected.col=Math.min(v[0].length-1,inspected.col+1);if(e.key==='ArrowUp')inspected.row=Math.max(0,inspected.row-1);if(e.key==='ArrowDown')inspected.row=Math.min(v.length-1,inspected.row+1);if(e.key==='Enter'){selectDetailCell(inspected.map,inspected.row,inspected.col)}showInspection()})}
function buildStages(){
 closeDetailPanel();maps.length=0;const overview=document.querySelector('.overview');overview.style.setProperty('--blocks',data.config.layers);const columns=data.config.layers>=4?data.config.layers/2:data.config.layers,rows=data.config.layers>=4?2:1;overview.style.setProperty('--block-cols',columns);overview.style.setProperty('--block-rows',rows);overview.classList.toggle('deep',rows===2);$('input-stage').style.gridColumn='1';$('input-stage').style.gridRow='1 / span '+rows;$('output-stage').style.gridColumn=String(columns+2);$('output-stage').style.gridRow='1 / span '+rows;
 overview.querySelectorAll('.decoder-stage').forEach(stage=>stage.remove());
 for(const id of ['input-maps','output-maps'])$(id).innerHTML='';
 for(let b=0;b<data.config.layers;b++){const stage=document.createElement('article');stage.className='stage decoder-stage';stage.style.gridColumn=String(b%columns+2);stage.style.gridRow=String(Math.floor(b/columns)+1);stage.id='block'+b+'-stage';stage.innerHTML=`<div class="stage-head"><h2>${String(b+2).padStart(2,'0')} <span>Decoder block ${b+1}</span></h2><span>1 head</span></div><div class="block-maps" id="block${b}-maps"></div>`;overview.insertBefore(stage,$('output-stage'))}


addMap('input-maps','tokenEmbedding','文字 E','語彙 → 16成分');addMap('input-maps','positionEmbedding','位置 P','位置 → 16成分');addMap('input-maps','embedding','E + P','文字と位置を加算');
for(let b=0;b<data.config.layers;b++){let id=`block${b}-maps`;addMap(id,'normAttention','LN 1','入力を正規化',b);addMap(id,'q','Q','検索する',b);addMap(id,'k','K','照合する',b);addMap(id,'v','V','情報を渡す',b);addMap(id,'attention','Attention','softmax(QKᵀ / √16 + mask)',b,true);addMap(id,'attentionOutput','Proj','文脈を射影',b);addMap(id,'attentionResidual','+ 残差 1','入力を加算',b,false,true);addMap(id,'normFF','LN 2','MLP前に正規化',b);addMap(id,'hidden','MLP hidden','16 → 32 · tanh',b);addMap(id,'ffOutput','MLP out','32 → 16',b);addMap(id,'output','+ 残差 2','ブロック出力',b,false,true)}
addMap('output-maps','finalNorm','Final LN','最終表現の正規化');addMap('output-maps','logits','Logits','16成分 → 全語彙');addMap('output-maps','probs','Softmax','全位置の次文字の確率');
}
function rgb(v,prob){let a,b=[20,39,50],t;if(prob){a=[137,239,187];t=Math.max(0,Math.min(1,v))}else{a=v>=0?[137,239,187]:[182,161,237];t=Math.min(1,Math.abs(v)/2)}return `rgb(${a.map((x,i)=>Math.round(b[i]+(x-b[i])*t)).join(',')})`}
function drawMap(map){let c=$(map.id),m=matrix(map),n=m.length,cols=m[0].length;const rect=c.getBoundingClientRect();if(rect.width<=0||rect.height<=0)return;const dpr=Math.min(window.devicePixelRatio||1,2);let w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(c.width!==w)c.width=w;if(c.height!==h)c.height=h;const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);let width=w/dpr,height=h/dpr,cw=width/cols,ch=height/n;ctx.clearRect(0,0,width,height);for(let i=0;i<n;i++)for(let j=0;j<cols;j++){let masked=map.key==='attention'&&j>i;ctx.fillStyle=masked?'#263440':rgb(m[i][j],map.key==='attention'||map.key==='probs');ctx.fillRect(j*cw,i*ch,Math.max(.5,cw-(cw>4?1:0)),Math.max(.5,ch-(ch>4?1:0)));if(masked&&cw>4){ctx.beginPath();ctx.strokeStyle='#3b4d58';ctx.lineWidth=.6;ctx.moveTo(j*cw,i*ch+ch);ctx.lineTo(j*cw+cw,i*ch);ctx.stroke()}}ctx.strokeStyle='#cdf5df';ctx.lineWidth=1;ctx.strokeRect(.5,position*ch+.5,Math.max(0,width-1),Math.max(0,ch-1));if(map.key==='attention'){ctx.strokeStyle='#a5c6b6';ctx.setLineDash([2,3]);ctx.beginPath();ctx.moveTo((position+.5)*cw,0);ctx.lineTo((position+.5)*cw,height);ctx.stroke();ctx.setLineDash([])}if(selectedCell&&selectedCell.map===map){let i=Math.min(selectedCell.row,n-1),j=Math.min(selectedCell.col,cols-1);ctx.strokeStyle='#ffd18a';ctx.lineWidth=2;ctx.strokeRect(j*cw+1,i*ch+1,Math.max(1,cw-2),Math.max(1,ch-2))}$(map.id+'-shape').textContent=n+'×'+cols;c.setAttribute('aria-description',`${n}位置・${cols}列。選択位置${position}。方向キーでセルを選択、Enterでセル詳細を開きます。予測位置は上部の文字ボタンで変更します。`)}
function inspectPointer(ev,map,choose){const rect=$(map.id).getBoundingClientRect(),m=matrix(map),row=Math.min(m.length-1,Math.max(0,Math.floor((ev.clientY-rect.top)/rect.height*m.length))),col=Math.min(m[0].length-1,Math.max(0,Math.floor((ev.clientX-rect.left)/rect.width*m[0].length)));inspected={map,row,col};if(choose){selectDetailCell(map,row,col)}else showInspection()}
function visibleToken(t){return t==='〈始〉'?'始':t==='〈終〉'?'終':t}
function showInspection(){if(!inspected)return;let {map,row,col}=inspected,m=matrix(map);row=Math.min(row,m.length-1);col=Math.min(col,m[0].length-1);const val=m[row][col],label=labels[map.key],token=data.tokens[example][row];$('inspect-title').textContent=(map.block===undefined?'':`Block ${map.block+1} · `)+label[0];if(map.key==='attention')$('inspect-value').textContent=`位置${row}「${visibleToken(token)}」→位置${col}「${visibleToken(data.tokens[example][col])}」：${(val*100).toFixed(2)}%${col>row?'（未来・参照禁止）':''}`;else if(map.key==='probs')$('inspect-value').textContent=`位置${row}「${visibleToken(token)}」→「${data.vocab[col]}」：${(val*100).toFixed(2)}%`;else if(map.key==='logits')$('inspect-value').textContent=`位置${row}「${visibleToken(token)}」·「${data.vocab[col]}」= ${val.toFixed(4)}`;else $('inspect-value').textContent=`位置${row}「${visibleToken(token)}」· d${col+1} = ${val.toFixed(4)}`;$('inspect-desc').textContent=label[1]}
function drawLoss(){if(!data.snapshots.length)return;const c=$('loss-chart'),rect=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);if(!rect.width||!rect.height)return;c.width=Math.round(rect.width*dpr);c.height=Math.round(rect.height*dpr);const ctx=c.getContext('2d');ctx.scale(dpr,dpr);const w=rect.width,h=rect.height,pad=4,max=Math.max(...data.snapshots.flatMap(s=>[s.loss,s.evalLoss]))*1.08;ctx.strokeStyle='#2b414d';ctx.lineWidth=1;ctx.setLineDash([3,4]);for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(0,h*i/4);ctx.lineTo(w,h*i/4);ctx.stroke()}ctx.setLineDash([]);for(const [key,color] of [['loss','#89efbb'],['evalLoss','#ffd18a']]){ctx.beginPath();data.snapshots.forEach((s,i)=>{const x=pad+(w-2*pad)*s.step/data.config.totalSteps,y=h-pad-(h-2*pad)*s[key]/max;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();const s=data.snapshots[frame];ctx.beginPath();ctx.arc(pad+(w-2*pad)*s.step/data.config.totalSteps,h-pad-(h-2*pad)*s[key]/max,3,0,Math.PI*2);ctx.fillStyle=color;ctx.fill()}}
function defaultPosition(){const ts=data.tokens[example],slash=ts.indexOf('／'),i=slash>=0?slash:ts.indexOf('。');return i>=0?i:Math.max(0,ts.length-2)}
function generationLimit(){return Math.max(40,data.config.maxContext)}
function renderTokens(){$('tokens').innerHTML=data.tokens[example].map((t,i)=>`<button class="tok ${i===position?'selected':''} ${i>position?'future':''} ${t==='〈始〉'?'special':''}" data-pos="${i}" aria-pressed="${i===position}" aria-label="位置${i}、${visibleToken(t)}。ここまでで次の文字を予測">${visibleToken(t)}</button>`).join('');$('tokens').querySelectorAll('[data-pos]').forEach(b=>b.onclick=()=>{position=+b.dataset.pos;render()})}
function renderPrediction(){const ex=current(),target=data.targets[example][position],targetId=data.vocab.indexOf(target),probs=ex.probs[position],ranking=probs.map((v,i)=>({v,i})).sort((a,b)=>b.v-a.v),rank=ranking.findIndex(t=>t.i===targetId)+1;$('prediction').innerHTML=ranking.slice(0,6).map(t=>`<div class="prob-row ${t.i===targetId?'correct':''}"><span title="${data.vocab[t.i]}">${visibleToken(data.vocab[t.i])}</span><span class="prob-bar"><i style="width:${t.v*100}%"></i></span><b>${(t.v*100).toFixed(1)}%</b></div>`).join('');$('target').textContent=target;$('correct-token').textContent=target;$('correct-prob').textContent=(probs[targetId]*100).toFixed(1)+'%';$('correct-rank').textContent=`${rank}位 / ${data.vocab.length}語彙`;$('prediction-position').textContent=`位置 ${position} → ${position+1}`;const prefix=data.tokens[example].slice(1,position+1).join('');$('prefix').textContent=(prefix||'〈始〉')+' ▏';$('prefix').title=prefix}
let generationRunId=0,generationKey='',generationPending=Promise.resolve([]),generationShown=false,generationInputKey='',generationBusy=false,generationResolve=null,generationTimer=null,lastGenerationShown=0,lastGenerationRequest=0;
function showGenerations(results,scope){generationShown=true;lastGenerationShown=performance.now();$('generation-step').textContent=`${scope.layers}層・${scope.dimension}d / 更新 ${scope.step}`;$('generation-step').title='表示中の候補の入力：'+(scope.prefix||'〈始〉');$('generation-results').innerHTML=results.map((r,i)=>{const tail=r.tokens.map(id=>data.vocab[id]).join(''),text=scope.prefix+(tail||'〈終〉');return `<div class="generation-result" title="${text}"><span class="generation-rank">${i+1}</span><span class="generation-result-text"><span>${scope.prefix}</span><strong>${tail||'〈終〉'}</strong></span><span class="generation-score">${r.score.toFixed(3)}</span><span class="generation-stop">${r.reason==='eos'?'終':'上限'}</span></div>`}).join('');$('generation-results').setAttribute('aria-busy','false');$('generation-end').textContent=results.length+'候補 · スコア順（大きいほど上位）'}
function cancelGeneration(){clearTimeout(generationTimer);generationTimer=null;generationRunId++;generationBusy=false;generationResolve?.([]);generationResolve=null;inferWorker.postMessage({type:'cancel'})}
function renderGeneration(force=false){if(!data.snapshots.length)return;const s=data.snapshots[frame],inputKey=modelSerial+':'+example+':'+position,key=inputKey+':'+s.step,inputChanged=inputKey!==generationInputKey;if(inputChanged){cancelGeneration();generationInputKey=inputKey;force=true}if(generationBusy)return;if(key===generationKey&&!force)return;const wait=4000-(performance.now()-lastGenerationShown);if(!force&&generationShown&&wait>0){if(!generationTimer)generationTimer=setTimeout(()=>{generationTimer=null;renderGeneration()},wait);return}clearTimeout(generationTimer);generationTimer=null;generationKey=key;const requestId=++generationRunId;generationBusy=true;lastGenerationRequest=performance.now();generationPending=new Promise(resolve=>{generationResolve=resolve});const scope={prefix:data.tokens[example].slice(1,position+1).join(''),step:s.step,layers:data.config.layers,dimension:data.config.dimension};$('generation-results').setAttribute('aria-busy','true');if(!generationShown){$('generation-step').textContent=`${scope.layers}層・${scope.dimension}d / 更新 ${scope.step}`;$('generation-results').textContent='上位5候補を探索中…'}$('generation-end').textContent=`${generationShown?'前の候補を表示中 · ':''}更新 ${scope.step} を探索中`;inferWorker.postMessage({type:'generate',requestId,weights:s.weights,seed:data.tokens[example].slice(0,position+1).map(t=>data.vocab.indexOf(t)),limit:generationLimit(),scope})}
inferWorker.onmessage=event=>{const m=event.data;if(m.requestId!==generationRunId)return;generationBusy=false;const resolve=generationResolve;generationResolve=null;if(m.type==='generated'){showGenerations(m.results,m.scope);resolve?.(m.results);renderGeneration()}else{$('generation-results').setAttribute('aria-busy','false');$('generation-end').textContent='生成を完了できませんでした：'+m.message;resolve?.([])}};
function render(){if(!data.snapshots.length)return;const s=data.snapshots[frame];$('step').textContent=s.step;$('seen').textContent=s.seen.toLocaleString()+'件 · '+(s.seen/data.config.trainCount).toFixed(2)+'周';$('training-progress').value=s.seen/(data.config.trainCount*data.config.epochs);$('epoch-label').textContent='目標'+data.config.epochs+'周';$('loss').textContent=s.evalLoss.toFixed(3);$('loss-change').textContent=`訓練 ${s.loss.toFixed(3)} · 正解 ${(s.accuracy*100).toFixed(1)}%`;$('play').textContent=playing?'一時停止':s.seen>=data.config.trainCount*data.config.epochs?'さらに4周':'学習開始';$('status').textContent=playing?'この端末で学習中 · 順伝播 → 逆伝播 → Adam更新':'文字で予測位置を変更 · セルで詳細を確認';$('phase').textContent=`${s.workMs? s.workMs.toFixed(0)+'ms / 更新 · ':''}${data.config.parameters.toLocaleString()}パラメータ`;renderTokens();renderPrediction();renderGeneration();maps.forEach(drawMap);drawLoss();if(selectedCell)renderCellDetails();if(inspected)showInspection();else{$('inspect-title').textContent='実値';$('inspect-value').textContent='行＝文字の位置 ／ 列＝成分。クリックで実値と計算を確認'}}
function stop(){playing=false;trainWorker.postMessage({type:'pause'});if(data.snapshots.length)$('play').textContent='学習開始'}
function start(){playing=true;trainWorker.postMessage({type:'start'});render()}
function updateModelLabels(){const cfg=data.config;$('generation-limit').textContent='ビーム幅5 · 最大'+generationLimit()+'文字';$('config').textContent=`WASM LIVE · ${cfg.layers} layers · ${cfg.dimension}d · ${cfg.parameters.toLocaleString()} params`;$('vocab-count').textContent=data.vocab.length+'語彙';$('total-steps').textContent='/ '+cfg.totalSteps;$('loss-end').textContent=cfg.totalSteps+'更新';$('training-details').textContent=`文字単位、語彙${data.vocab.length}、最大文脈${cfg.maxContext}位置。${cfg.layers}ブロック・各1ヘッド・${cfg.dimension}次元・MLP隠れ${cfg.ff}次元。Pre-LayerNorm、因果Attention、残差接続、tanh MLP。Adam、学習率${cfg.learningRate}、勾配ノルムを1に制限、バッチ${cfg.batchSize}。学習対象${cfg.trainCount.toLocaleString()}件をシャッフル。設定の変更で学習を初期化します。`}
let initRequestId=0,acceptedVersion=null,pendingConfig=null,readyResolve=null,engineReady=Promise.resolve(),lastHeartbeat=performance.now(),checkpoint=null,recoveryCount=0,recovering=false;
function unpackWeights(flat,shapes){const out={};let offset=0;for(const [key,[rows,cols]] of Object.entries(shapes)){out[key]=Array.from({length:rows},()=>{const row=Array.from(flat.subarray(offset,offset+cols));offset+=cols;return row})}return out}
function handleTrainingMessage(event){const m=event.data;lastHeartbeat=performance.now();if(m.type==='error'){playing=false;$('status').textContent=m.message;setTrainingDisabled(false);return}if(m.type==='state'&&m.ready){if(m.requestId!==initRequestId)return;acceptedVersion=m.version;if(!m.resumed){data={...archiveData,config:{...pendingConfig,parameters:m.parameters},snapshots:[]};frame=0;modelSerial++;activeModelId=data.config.layers+'-'+data.config.dimension;currentTraceKey='';detailTraceKey='';baselineTraceCache.clear();inspected=null;selectedCell=null}recovering=false}else if(m.version!==acceptedVersion)return;if(m.type==='running'){playing=m.running;data.config.epochs=m.limit;data.config.totalSteps=Math.ceil(data.config.trainCount/data.config.batchSize)*m.limit;updateModelLabels();render();return}if(m.type!=='state')return;checkpoint=m.checkpoint;playing=m.running;data.config.epochs=m.limit;data.config.totalSteps=Math.ceil(data.config.trainCount/data.config.batchSize)*m.limit;const s={step:m.step,seen:m.seen,loss:m.loss,evalLoss:m.evalLoss,accuracy:m.accuracy,grad:m.grad,workMs:m.workMs,weights:unpackWeights(m.weights,m.shapes)};if(data.snapshots.length&&data.snapshots.at(-1).step===s.step)data.snapshots[data.snapshots.length-1]=s;else{if(frame>0)delete data.snapshots[frame].weights;data.snapshots.push(s)}frame=data.snapshots.length-1;if(m.ready){setTrainingDisabled(false);if(!m.resumed)buildStages();$('architecture-status').textContent='構成変更で重みを初期化';readyResolve?.();readyResolve=null}updateModelLabels();render()};
function setTrainingDisabled(disabled){for(const id of ['play','next','reset','dataset','layer-count','dimension-count','batch-size'])$(id).disabled=disabled}
function initializeModel(){readyResolve?.();readyResolve=null;checkpoint=null;recoveryCount=0;recovering=false;lastHeartbeat=performance.now();const requestId=++initRequestId;acceptedVersion=null;playing=false;cancelGeneration();generationInputKey='';pendingConfig={dimension:+$('dimension-count').value,layers:+$('layer-count').value,ff:+$('dimension-count').value*2,heads:1,maxContext:Math.max(...archiveData.rows.map(r=>r.length))-1,trainCount:archiveData.trainIndices.length,testCount:archiveData.testIndices.length,batchSize:+$('batch-size').value,learningRate:.003,epochs:4,totalSteps:Math.ceil(archiveData.trainIndices.length/+$('batch-size').value)*4};setTrainingDisabled(true);$('architecture-status').textContent='初期重みを準備中…';$('status').textContent='WASM学習エンジンを準備中';engineReady=new Promise(resolve=>{readyResolve=resolve});trainWorker.postMessage({type:'init',requestId,dimension:pendingConfig.dimension,layers:pendingConfig.layers,context:pendingConfig.maxContext,batchSize:pendingConfig.batchSize,learningRate:pendingConfig.learningRate,wasm:wasmBytes,corpus:{vocab:archiveData.vocab,rows:archiveData.rows,trainIndices:archiveData.trainIndices,testIndices:archiveData.testIndices}});return engineReady}
function renderDatasetInfo(){const d=archiveData;$('corpus-count').textContent=d.corpusRecords.length.toLocaleString()+d.unit;$('corpus-split').textContent=`${d.summary} · 学習${d.trainIndices.length.toLocaleString()} / 評価${d.testIndices.length.toLocaleString()}`;$('example-label').textContent=d.label;$('dataset-about').innerHTML=d.about;$('generation-limit').textContent='ビーム幅5 · 最大'+Math.max(40,Math.max(...d.rows.map(r=>r.length))-1)+'文字';$('example').innerHTML=d.texts.map((t,i)=>`<option value="${i}">${d.exampleSplits[i]==='test'?'評価':'訓練'} · ${t}</option>`).join('');$('example').value='0'}
$('dataset').innerHTML=datasets.map((d,i)=>`<option value="${i}">${d.label}（${d.corpusRecords.length.toLocaleString()}${d.unit}）</option>`).join('');
// Switching data changes the vocabulary and context length, so the model restarts from fresh weights.
$('dataset').onchange=()=>{archiveData=datasets[+$('dataset').value];data={...archiveData,config:data.config,snapshots:[]};example=0;position=defaultPosition();inspected=null;closeDetailPanel();selectedCell=null;renderDatasetInfo();generationShown=false;$('generation-results').textContent='初期重みを準備中…';$('generation-step').textContent='';return initializeModel()};
renderDatasetInfo();$('example').onchange=()=>{example=+$('example').value;position=defaultPosition();inspected=null;closeDetailPanel();render()};$('play').onclick=()=>{playing?stop():start();render()};$('next').onclick=()=>{playing=false;trainWorker.postMessage({type:'step'})};$('reset').onclick=initializeModel;for(const id of ['layer-count','dimension-count','batch-size'])$(id).onchange=initializeModel;
$('about').onclick=()=>$('info').showModal();$('close-info').onclick=()=>$('info').close();$('download-corpus').onclick=()=>{const fields=Object.keys(archiveData.corpusRecords[0]),q=v=>'"'+String(v).replaceAll('"','""')+'"',csv='\ufeff'+fields.join(',')+'\r\n'+archiveData.corpusRecords.map(r=>fields.map(k=>q(r[k])).join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=archiveData.csvName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
if(document.documentElement.requestFullscreen){$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{$('status').textContent='ウィンドウを広げてご覧ください。'}};document.addEventListener('fullscreenchange',()=>requestAnimationFrame(render))}else $('fullscreen').hidden=true;
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(data.snapshots.length){maps.forEach(drawMap);drawLoss()}},80)});position=defaultPosition();$('architecture-controls').hidden=false;
function recoverTraining(){if(recovering)return;if(!checkpoint||recoveryCount>=2){playing=false;$('status').textContent='学習処理が応答しません。初期化で再開できます。';setTrainingDisabled(false);return}recovering=true;recoveryCount++;const resume=playing;trainWorker.terminate();trainWorker=makeWorker('train-worker');bindTrainingWorker();acceptedVersion=null;lastHeartbeat=performance.now();const requestId=++initRequestId;setTrainingDisabled(true);$('status').textContent='応答の停滞を検出 · 更新 '+checkpoint.step+' から復元中';trainWorker.postMessage({type:'init',requestId,dimension:data.config.dimension,layers:data.config.layers,context:data.config.maxContext,batchSize:data.config.batchSize,learningRate:data.config.learningRate,wasm:wasmBytes,corpus:{vocab:archiveData.vocab,rows:archiveData.rows,trainIndices:archiveData.trainIndices,testIndices:archiveData.testIndices},checkpoint,resume})}
function bindTrainingWorker(){const worker=trainWorker;worker.onmessage=event=>{if(worker===trainWorker)handleTrainingMessage(event)};worker.onerror=()=>{if(worker===trainWorker){recovering=false;recoverTraining()}}}
bindTrainingWorker();

inferWorker.onerror=e=>{generationBusy=false;generationResolve?.([]);generationResolve=null;$('generation-end').textContent='生成処理を開始できませんでした：'+e.message};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'control_training',description:'この端末上のTransformerを実際に学習・停止・1更新・初期化し、現在の評価値を返す。構成変更はUIで行う。',inputSchema:{type:'object',properties:{action:{type:'string',enum:['inspect','start','pause','step','reset']}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){if(!input||!['inspect','start','pause','step','reset'].includes(input.action))throw Error('学習操作が不正です');await engineReady;if(input.action==='start')start();if(input.action==='pause')stop();if(input.action==='step'){$('next').onclick()}if(input.action==='reset')await initializeModel();const s=data.snapshots[frame];return {configuration:activeModelId,step:s.step,seen:s.seen,trainLoss:s.loss,validationLoss:s.evalLoss,validationAccuracy:s.accuracy,running:playing}}})).catch(()=>{})}catch{}}

let watchdogTimer=null;function watchdog(){const now=performance.now();if((playing||acceptedVersion===null)&&now-lastHeartbeat>30000){recovering=false;recoverTraining();lastHeartbeat=now}if(generationBusy&&now-lastGenerationRequest>60000){const old=inferWorker.onmessage;inferWorker.terminate();inferWorker=makeWorker('infer-worker');inferWorker.onmessage=old;generationBusy=false;generationResolve?.([]);generationResolve=null;generationKey='';renderGeneration(true)}watchdogTimer=setTimeout(watchdog,1000)}watchdog();
