const fs=require('fs'),assert=require('assert');const {WasmTransformer}=require('./engine.js');const {decoderTrace}=require('./decoder.js');
(async()=>{const bytes=fs.readFileSync(__dirname+'/engine.wasm'),data=JSON.parse(fs.readFileSync(__dirname+'/corpus-common.json'));let engine=await WasmTransformer.create(bytes,{dimension:8,layers:2,vocabSize:data.vocab.length,context:21});const packed=engine.packRows(data.rows,[0,1]),s=engine.batch(packed.tokens,packed.targets,true),gradient=engine.view(engine.g,engine.count).slice();const probabilities=engine.view(s.probsPtr,s.rows*engine.v).slice();
const trace=decoderTrace(engine.arrays(),data.rows[0].slice(0,-1));let maximum=0;for(let i=0;i<trace.probs.length;i++)for(let j=0;j<engine.v;j++)maximum=Math.max(maximum,Math.abs(probabilities[i*engine.v+j]-trace.probs[i][j]));assert(maximum<1e-5,maximum);console.log('PASS inference agreement with independent JS:',maximum,'loss',s.loss);
for(const key of ['head','0q','0f','E','P']){const tensor=engine.weights[key];for(const index of key==='E'?[data.rows[0][2]*engine.d+3,engine.d+3]:[1,Math.floor(tensor.r*tensor.c/3)]){const offset=(tensor.ptr-engine.p)/4+index,base=engine.view(engine.p,engine.count)[offset],eps=.002;engine.view(engine.p,engine.count)[offset]=base+eps;const plus=engine.batch(packed.tokens,packed.targets).loss;engine.view(engine.p,engine.count)[offset]=base-eps;const minus=engine.batch(packed.tokens,packed.targets).loss;engine.view(engine.p,engine.count)[offset]=base;const numeric=(plus-minus)/(2*eps),analytical=gradient[offset];assert(Math.abs(numeric-analytical)<.002,JSON.stringify({key,index,numeric,analytical}));console.log('PASS gradient',key,index,numeric.toFixed(6),analytical.toFixed(6))}}
const pool=data.trainIndices.slice(0,32),initial=engine.evaluate(data.rows,pool).loss,before=engine.copyWeights();let start=Date.now();for(let step=0;step<80;step++)engine.train(data.rows,pool.slice(step%2*16,(step%2+1)*16));const final=engine.evaluate(data.rows,pool).loss;assert(final<initial*.65,{initial,final});assert(engine.copyWeights().some((x,i)=>x!==before[i]));console.log('PASS real training',initial,'->',final,'80 updates',Date.now()-start,'ms');
for(const layers of [2,4,6])for(const dimension of [8,16,32,48,64]){engine=await WasmTransformer.create(bytes,{dimension,layers,vocabSize:data.vocab.length,context:21});const start=Date.now(),stats=engine.train(data.rows,data.trainIndices.slice(0,16));assert(Number.isFinite(stats.loss)&&Number.isFinite(stats.grad));console.log('PASS configuration',layers,dimension,'params',engine.count,'update ms',Date.now()-start,'memory MiB',engine.memory.buffer.byteLength/1048576)}
// Multi-head attention: JS inference matches Wasm, gradients match finite differences, and the head count changes the function.
for(const heads of [2,4]){const e=await WasmTransformer.create(bytes,{dimension:16,layers:2,heads,vocabSize:data.vocab.length,context:21});for(let i=0;i<20;i++)e.train(data.rows,data.trainIndices.slice(i*16,i*16+16));const p=e.packRows(data.rows,[0,1]),st=e.batch(p.tokens,p.targets,true),grad=e.view(e.g,e.count).slice(),probs=e.view(st.probsPtr,st.rows*e.v).slice(),w=e.arrays();assert.equal(w.heads,heads);
 const tr=decoderTrace(w,data.rows[0].slice(0,-1));let mx=0;for(let i=0;i<tr.probs.length;i++)for(let j=0;j<e.v;j++)mx=Math.max(mx,Math.abs(probs[i*e.v+j]-tr.probs[i][j]));assert(mx<1e-5,mx);assert.equal(tr.blocks[0]['attention'+(heads-1)].length,tr.probs.length);
 // Relative error over every 7th entry with a gradient large enough to resolve in float32.
 const p4=e.packRows(data.rows,[0,1,2,3]);e.batch(p4.tokens,p4.targets,true);const g4=e.view(e.g,e.count).slice(),rel=[];for(const key of ['0q','0k','1v']){const t=e.weights[key];for(let index=0;index<t.r*t.c;index+=7){const off=(t.ptr-e.p)/4+index,base=e.view(e.p,e.count)[off],eps=.02;e.view(e.p,e.count)[off]=base+eps;const plus=e.batch(p4.tokens,p4.targets).loss;e.view(e.p,e.count)[off]=base-eps;const minus=e.batch(p4.tokens,p4.targets).loss;e.view(e.p,e.count)[off]=base;if(Math.abs(g4[off])>2e-3)rel.push(Math.abs((plus-minus)/(2*eps)-g4[off])/Math.abs(g4[off]))}}rel.sort((a,b)=>a-b);assert(rel.length>30&&rel[rel.length>>1]<.01&&rel.at(-1)<.05,JSON.stringify({heads,median:rel[rel.length>>1],max:rel.at(-1)}));
 const single={...w,heads:1};assert(Math.abs(decoderTrace(single,data.rows[0].slice(0,-1)).probs[5][7]-tr.probs[5][7])>1e-9);
 console.log('PASS multi-head',heads,'inference agreement',mx,'gradient median relative error',rel[rel.length>>1].toFixed(4))}
})().catch(e=>{console.error(e);process.exitCode=1});
