'use strict';
let engine=null,corpus=null,version=0,running=false,timer=null,order=[],cursor=0,epochsDone=0,seen=0,limit=4,batchSize=16,lr=.003,lastSent=0,lastGrad=0,shuffleState=2026,trainSample=[],testSample=[],lastWorkMs=0;
function shuffle(items){const copy=items.slice();for(let i=copy.length-1;i>0;i--){shuffleState^=shuffleState<<13;shuffleState^=shuffleState>>>17;shuffleState^=shuffleState<<5;const j=(shuffleState>>>0)%(i+1);[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function sample(items,seed,count=128){let s=seed>>>0;const copy=items.slice();for(let i=copy.length-1;i>0;i--){s=(Math.imul(s,1664525)+1013904223)>>>0;const j=s%(i+1);[copy[i],copy[j]]=[copy[j],copy[i]]}return copy.slice(0,count)}
function publish(extra={}){if(!engine)return;const train=engine.evaluate(corpus.rows,trainSample),test=engine.evaluate(corpus.rows,testSample),weights=engine.copyWeights(),mom=engine.view(engine.m,engine.count).slice(),variance=engine.view(engine.vv,engine.count).slice(),checkpoint={weights,mom,variance,step:engine.step,seen,epochsDone,cursor,order:order.slice(),shuffleState,limit,lastGrad,dimension:engine.d,layers:engine.l,batchSize};lastSent=performance.now();postMessage({type:'state',version,step:engine.step,seen,epochsDone,loss:train.loss,evalLoss:test.loss,accuracy:test.accuracy,grad:lastGrad,running,limit,workMs:lastWorkMs,shapes:engine.shapes,parameters:engine.count,memory:engine.memory.buffer.byteLength,weights,checkpoint,...extra},[weights.buffer,mom.buffer,variance.buffer])}
function advance(){const ids=order.slice(cursor,cursor+batchSize),start=performance.now();const stats=engine.train(corpus.rows,ids,lr);lastWorkMs=performance.now()-start;lastGrad=stats.grad;cursor+=ids.length;seen+=ids.length;if(cursor>=order.length){epochsDone++;cursor=0;order=shuffle(corpus.trainIndices)}return ids.length}
function tick(){timer=null;if(!running||!engine)return;const turnVersion=version;try{advance();if(epochsDone>=limit){running=false;publish({complete:true});return}if(performance.now()-lastSent>=500)publish();if(running&&turnVersion===version)timer=setTimeout(tick,0)}catch(error){running=false;postMessage({type:'error',version,message:error.message})}}
onmessage=async event=>{const m=event.data;try{
 if(m.type==='init'){const current=++version;running=false;clearTimeout(timer);timer=null;engine=null;corpus=m.corpus;batchSize=m.batchSize||16;lr=m.learningRate||.003;limit=4;epochsDone=0;cursor=0;seen=0;lastGrad=0;lastWorkMs=0;shuffleState=2026;const e=await WasmTransformer.create(m.wasm,{dimension:m.dimension,layers:m.layers,vocabSize:corpus.vocab.length,context:m.context,seed:42});if(current!==version)return;engine=e;order=shuffle(corpus.trainIndices);trainSample=sample(corpus.trainIndices,123);testSample=sample(corpus.testIndices,456);if(m.checkpoint){const cp=m.checkpoint;if(cp.weights.length!==engine.count||cp.dimension!==engine.d||cp.layers!==engine.l)throw Error('復元する構成が一致しません');engine.view(engine.p,engine.count).set(cp.weights);engine.view(engine.m,engine.count).set(cp.mom);engine.view(engine.vv,engine.count).set(cp.variance);engine.step=cp.step;seen=cp.seen;epochsDone=cp.epochsDone;cursor=cp.cursor;order=cp.order.slice();shuffleState=cp.shuffleState;limit=cp.limit;lastGrad=cp.lastGrad;running=!!m.resume}publish({ready:true,resumed:!!m.checkpoint,requestId:m.requestId});if(running)timer=setTimeout(tick,0);return}
 if(!engine)return;
 if(m.type==='start'){if(running)return;if(epochsDone>=limit)limit+=4;running=true;postMessage({type:'running',version,running:true,limit});tick()}
 if(m.type==='pause'){running=false;clearTimeout(timer);timer=null;publish({paused:true})}
 if(m.type==='step'){running=false;clearTimeout(timer);timer=null;if(epochsDone>=limit)limit+=4;advance();publish({paused:true})}
 if(m.type==='snapshot')publish();
}catch(error){running=false;postMessage({type:'error',version,message:error.message})}};
